### PR TITLE
Fix the missing class in the AR validator

### LINKED ISSUE #431: 6.3.0: `NoMethodError: undefined method '<' for nil:NilClass` when using a factory with traits
### Description

After upgrading to 6.3.0, specs with traits started failing.

Downgrade to 6.2.0 works.

The problem seems to be triggered here: 

https://github.com/thoughtbot/factory_bot_rails/blob/3346305320df35eadae4ac942e44fa7adbbfa574/lib/factory_bot_rails/factory_validator/active_record_validator.rb#L7

`for_class` is nil because the payload contains `class: nil`

### Reproduction Steps

Please checkout the branch https://github.com/diowa/ruby3-rails7-bootstrap-heroku/tree/tmp/factory-bot-rails-issue

and run `bundle exec rspec spec/model/user_spec.rb`

Relevant commit: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/commit/3c839031021362139ec9819bb51fdc861b337dcb

### Expected behavior

Objects being created as 6.2.0

### Actual behavior

```
       expected no Exception, got #<NoMethodError: undefined method `<' for nil:NilClass> with backtrace:
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator/active_record_validator.rb:7:in `block in validate!'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/attribute_list.rb:19:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/attribute_list.rb:19:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator/active_record_validator.rb:6:in `validate!'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `block (2 levels) in rails_6_0_support'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `block in rails_6_0_support'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:61:in `compile'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:169:in `aggregate_from_traits_and_self'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:36:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/trait.rb:17:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:174:in `map'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:174:in `aggregate_from_traits_and_self'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:36:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition_hierarchy.rb:6:in `build_from_definition'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:125:in `build_hierarchy'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:88:in `compile'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:32:in `run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory_runner.rb:28:in `run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
         # ./spec/model/user_spec.rb:8:in `block (3 levels) in <top (required)>'
         # ./spec/model/user_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ~/.rvm/gems/ruby-3.2.2/gems/webmock-3.19.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

### System configuration
**factory_bot_rails version**:  6.3.0
**factory_bot version**:  6.4.0
**rails version**:  7.1.2
**ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by elia**
Fixes #431

Not completely sure what's going on, except skipping the validation if there's no class. This is meant to be a temporary hot fix to save people from downgrading to 6.2. Will surely require further investigation.

### CODE REVIEW

**Comment by elia** [comment]
Fixed in factory_bot 6.4.2
