### ISSUE TITLE
6.3.0: `NoMethodError: undefined method '<' for nil:NilClass` when using a factory with traits

### ISSUE THREAD

**Issue by tagliala** [thoughtbot/factory_bot_rails#431]
### Description

After upgrading to 6.3.0, specs with traits started failing.

Downgrade to 6.2.0 works.

The problem seems to be triggered here: 

https://github.com/thoughtbot/factory_bot_rails/blob/3346305320df35eadae4ac942e44fa7adbbfa574/lib/factory_bot_rails/factory_validator/active_record_validator.rb#L7

`for_class` is nil because the payload contains `class: nil`

### Reproduction Steps

Please checkout the branch https://github.com/diowa/ruby3-rails7-bootstrap-heroku/tree/tmp/factory-bot-rails-issue

and run `bundle exec rspec spec/model/user_spec.rb`

Relevant commit: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/commit/3c839031021362139ec9819bb51fdc861b337dcb

### Expected behavior

Objects being created as 6.2.0

### Actual behavior

```
       expected no Exception, got #<NoMethodError: undefined method `<' for nil:NilClass> with backtrace:
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator/active_record_validator.rb:7:in `block in validate!'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/attribute_list.rb:19:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/attribute_list.rb:19:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator/active_record_validator.rb:6:in `validate!'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `block (2 levels) in rails_6_0_support'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `each'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot_rails-6.3.0/lib/factory_bot_rails/factory_validator.rb:27:in `block in rails_6_0_support'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:61:in `compile'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:169:in `aggregate_from_traits_and_self'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:36:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/trait.rb:17:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:174:in `map'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:174:in `aggregate_from_traits_and_self'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition.rb:36:in `to_create'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/definition_hierarchy.rb:6:in `build_from_definition'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:125:in `build_hierarchy'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:88:in `compile'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory.rb:32:in `run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/factory_runner.rb:28:in `run'
         # ~/.rvm/gems/ruby-3.2.2/gems/factory_bot-6.4.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
         # ./spec/model/user_spec.rb:8:in `block (3 levels) in <top (required)>'
         # ./spec/model/user_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ~/.rvm/gems/ruby-3.2.2/gems/webmock-3.19.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

### System configuration
**factory_bot_rails version**:  6.3.0
**factory_bot version**:  6.4.0
**rails version**:  7.1.2
**ruby version**: 3.2.2

**Comment by guperrot** [comment]
We have the same issue too, preventing us from upgrading the lib.
We are trying to call a method defined in a factory in another file:

```
FactoryBot.define do
  factory :B do
    tenant { create :A, status: "enabled" }
```

And we get the same error at the `tenant` line, which was working fine in 6.2.0.

factory_bot_rails version: 6.4.0
factory_bot version: 6.4.0
rails version: 7.1.2
ruby version: 3.1.3

**Comment by guperrot** [comment]
We have the same issue too, preventing us from upgrading the lib.
We are trying to call a method defined in a factory in another file:

```
FactoryBot.define do
  factory :bbb do
    aaa { create :aaa, status: "enabled" }
```

And we get the same error at the `aaa` line, which was working fine in 6.2.0.

factory_bot_rails version: 6.4.0
factory_bot version: 6.4.0
rails version: 7.1.2
ruby version: 3.1.3

**Comment by troya2** [comment]
I don't have a full grasp on what's happening, but I have traced the code and this happens when the factory_bot.compile_factory notification is sent from FacyoryBot with a nil class, which occurs when FactoryBot is sends this notification for defined traits.  The ActiveRecordValidator class's validate! method processes the event and assumes class will not be nil and throws this exception.

**Comment by gaffneyc** [comment]
Just tried updating to FactoryBot to 6.4.1 and I'm still seeing this issue. The best I can figure out is that it happens the first time we create a factory which has a trait with the same name as an attribute (e.g. `create(:user, :admin)` where the User class has an `admin` trait and an `admin` column).

**Comment by davidrunger** [comment]
FWIW, bumping to `factory_bot (6.4.1)` and `factory_bot_rails (6.4.0)` did resolve this issue on my repo. Thanks for the quick (partial?) fix!

**Comment by mudge** [comment]
After upgrading to factory_bot 6.4.1 and factory_bot_rails 6.4.0, I'm still seeing the `undefined method < for nil:NilClass` error from `lib/factory_bot_rails/factory_validator/active_record_validator.rb:7:in block in validate!` when using a [mixin trait](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#as-mixins), e.g.

```ruby
FactoryBot.define do
  factory :magazine do
    # ...
  end

  trait :with_latest_issue do
    # ...
  end
end
```

Adding a `debugger` shows that the `payload` Hash passed to `validate!(payload)` for the `:with_latest_issue` trait has the `:class` key set to `nil`.

**Comment by sledge909** [comment]
> FWIW, bumping to `factory_bot (6.4.1)` and `factory_bot_rails (6.4.0)` did resolve this issue on my repo. Thanks for the quick (partial?) fix!

This worked for me too 👍

**Comment by gmmcal** [comment]
Bumping `factory_bot` to `6.4.1` also fixed for me on https://github.com/gmmcal/gmmcal.com.br/pull/1129

**Comment by mike-burns** [comment]
Note that due to a US holiday this week, and the family + travel leading up to and around that, I won't be able to debug this myself until December. But if someone opens a PR with a test, I can merge and release that.

**Comment by tagliala** [comment]
I cannot replicate the failure mentioned in the opening post with 6.4.1.

> the first time we create a factory which has a trait with the same name as an attribute (e.g. create(:user, :admin) where the User class has an admin trait and an admin column).

Literally the opening post (active with active field), but it works with 6.4.1

I've also tried enum's implicit traits and they worked

**Comment by tagliala** [comment]
> I'm noticing a weird behavior locally, on my first try it fails, on subsequent tries it works. This for factory_bot 6.4.1 and factory_bot_rails 6.4.0, **this happens on rails console.**

Thanks for the clarification! 

Confirmed it happening in the console

Replicable on the opening post application:

```
rails c
Loading development environment (Rails 7.1.2)
[1] pry(main)> FactoryBot.create :user, :active
NoMethodError: undefined method `<' for nil:NilClass
```

**Comment by PedroSena** [comment]
I do have spring, but I'm able to replicate the issue even when I remove it. One difference that I noticed is the rails version.
I'm on Rails 6.1.7.6. I'll try to isolate the problem with a standalone rails 6 app and update here soon

```
[1] pry(main)> FactoryBot.create(:pipeline_run_step_result, :discard)
NoMethodError: undefined method `<' for nil:NilClass
from /Users/psena/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/factory_bot_rails-6.4.0/lib/factory_bot_rails/factory_validator/active_record_validator.rb:7:in `block in validate!'
[2] pry(main)> FactoryBot::VERSION
=> "6.4.1"
[3] pry(main)> Rails.version
=> "6.1.7.6"
```

**Comment by tagliala** [comment]
I've also tried to replicate with 6.1.7.6 without success. At the beginning it was failing, but I opened a new bash console and it stopped. I run it the first time with Spring

**Comment by Petercopter** [comment]
This is failing consistently for me locally and in the CI, but what's interesting is that the same factory with the same attributes/traits is being used in multiple tests, but only some of them are failing. I haven't found the rhyme or the reason yet.

**Comment by gaffneyc** [comment]
When I tested it out it appeared to be the first time a factory was created with a given trait or set of arguments so it would move around based on test execution order.

**Comment by elia** [comment]
@mike-burns @tagliala https://github.com/thoughtbot/factory_bot_rails/pull/437 is a hot fix, maybe until https://github.com/thoughtbot/factory_bot/pull/1601 is merged, even if #437 is not merged the spec in consistently fails without the patch and might be worth adding as regression avoidance.

**Comment by mike-burns** [comment]
Thank you to @makicamel for stepping up with a second fix, with great tests.

**Comment by rnestler** [comment]
>  This fix is released as 6.4.2.

Where can we find this 6.4.2 release? The latest tag on GitHub and version on rubygems.org is 6.4.0.

**Comment by mike-burns** [comment]
Sorry, the 6.4.2 release of factory_bot, which factory_bot_rails depends on. If you `bundle update factory_bot` it should pull in the latest dependency.

**Comment by rnestler** [comment]
> Sorry, the 6.4.2 release of factory_bot, which factory_bot_rails depends on. If you bundle update factory_bot it should pull in the latest dependency.

Ah this would actually have been clear if I read the comments above. It works now fine again with `factory_bot` `6.4.2` and `factory_bot_rails` `6.4.0`, thanks :slightly_smiling_face:
